language: android
android:
  components:
  - tools
  - tools
  - build-tools-26.0.0
  - android-25
  - extra-android-m2repository
jdk:
- oraclejdk8
after_success:
- build-scripts/deploy_snapshot.sh
env:
  global:
  - secure: H2gYRhr3Qh2gHTRyARHfDJTxUx7k5PDBF39OpN6NZSBkbyuF1o+e3ukTQhkkeiN3sCZsqsZbyfRl61XSPO10tSdEg6ttWL+vJjkmnjet9nGZqgylb/Xs7N6tMVeSGoHXhJ9dKHYc2HKlxJHFpeaIgmzytfYIlJ/9HYEqo12FbGK22/FMvmJIfbukPuvlnnMzPzRomJKXIzS4atc91NAK6cHKNGyVwzHGrNRjhScv4bG/20fYFEHIpAL/57jCDm9SKNwqn/a7Nlyf2dFy6faAQu3rrMubpbzTdATZQnjT5Tvb7OnQvISYb8iKRauAYbphGaxFGUfp3UxFnS7I6km4be47X430UUECxla5ZlJPc2NX1sNC4ut447EdspcaaF1an6iW9X/MBF0uGz51ubeg8a0denj2PULvhAiYgBZajjrSRM0gnnKAxgFgaWPJUBYz2/LYck+b8/or8EBDJW0+1RzktwunAQH6Pt2rZOdq/e62SLWFAh148W0yDFxx5/AI+nSw1IoHhtB4xd4Gv/jkiZm/LvhE+UYWrppUG2UR6wq8qH69c1v2ezDyqh7nSUia9MkWHbyd4FwvV7ki1s07P+tp9bvYXlGVeuIhlFEIxIR4pxmTsIZrT4KVaU/uTuTLsbOluxmil6DkdDEpqo/V2rmytIMVwWViXSCT7VgIDQU=
  - secure: u969ijVVMZSM4KL07vXbSN4os2mjEtYmRpvPMu83+LQEk4qVOe4rLNYaltvBocR3RpzlsnBbN9hrVI+NzPGpNa0dvioqPFVtqm8SUpHfF1+nHU3zLlfWCaEsn8d1YRVy5DK9yMPTjSPdSmS8S5EbZXoYP+LdpIuM08HRujoqn33wceHzFLz5gF8kiPQWTPDq33wwDd/C2JttnZ9IdRGMw74zNOB+z7L2eJkCcYMjEaO1bNUZHHIVdWK9AAlsxGH3UEQrkaWUGTikauutVEu6pA9k7muUOdrZwqfG67XzY9BZpn+KNXvfnVoi2Ps7158WIEDZKq6X989sEvaVbbDJ8ffvj+K2qR4MSRDOywPx89hH1JVHKGXGYW3qT/ypFBb1cTaP5zEV0WIpa81d9kiNTXwKGSxgME6qcFXQu5Ivga+9Jw6yYtpLoyyjzK3SaBXkemA6iUaVZr6oEVxRFVS7uGq1YYO8lmHVe6i3760YbZwfsGwI41V4Az6z63vSlk1f6Byzduy4+Qwrmd8rnBVSblVg0ykW/ulhxnaNgD/f/OJhACwyjmlG5f2omlDP8wkocPuv57rUqh+2hsFJFcbDShwbVKNIGRtUfDmOBKPhAKJIuxBIMapdBf99hOmM42c/smeSfBI/RA5y7BbLWYc22Ebu7+GidV8VJL8ey1oKP54=
sudo: false
cache:
  directories:
  - $HOME/.gradle
