language: android
android:
  components:
  - tools
  - tools
  - build-tools-26.0.0
  - android-25
  - extra-android-m2repository
jdk:
- oraclejdk8
after_success:
- build-scripts/deploy_snapshot.sh
env:
  global:
  - secure: Z3Sn8rLz4Ots1gkFBU9Du4r2hHmSn9rnSLeIiujZ+o3QZCUzGBfnGEgTQMCSsVjZC+9Tvr8ezWDU4Cqj+5cD3Nz06v5uUZL9zyp+N7/e8gV0uocgZgHehKZuKk+ctRwmqKH34DS7Nnvpu6ilvhxbHFpehlf3FDhZ24SlHPTpScSZyeSJhZNBBMUVATCyIu4VtH35HmsZJkYODSCpFHXxrBNrkOiEgOZ0gTQ66jUG1wikk7KvP5vq8ZBtFVeLpxYpLRYGoVc0IRMxdPDznXorMRB0jDO6ux/ElZr0CWfxDTLikU+JEMvUWXD8VzsNSP9RnuUU4ka18nkzddkkDWlqtE50FAiwIlSBynry/hYtbodMbwszUxV8oS9DImx0CBRzSRey3VdaycNdMpL/zTf2prMTLWTVpet+7Hrd2ciM4IPXdKJTxV3a+fnb24FIH36CZfF5GRUMu4+849wra4eUyzDNVV4pWRYiq5HY9C/fVZElml3Q9YjTM7xuslnaeMmD7fj8aej6LkH/uYcQTjV2crReUR+T53Jd2pVugTy6sQSyLAD5Y73UgxL0fbzhhxxfpeobdSnaG/7Tl666ci88Njv9Mn2yE1FjrNpWgmVjpS5MjNsk3MjVfekzHC32pcZzaqacJ8YT9nxHhNzKRmA4hC4mmO9N93YN+GXZ9kxpXDs=
  - secure: Y1c/XMA2cPwIN/ywNySmu1yqie2m9boO3mLvEzF7IVr7NUS3D81SuF+5uwWnEqLLHRLevqSLmWsa1Kt6xbzm38SRLb6sDDcYsB3RlD2cUy2cI89CJ9Eiu+4kFWB8d5i4Vz/ROtpux3Ya33G5mwtxNHEY0igTNsllG6/lhbxj9ZsXqDRkNFC0R1WbDSe7hWXUUe35Ttul0IWJfm5sYh3cHp+t/XBkX6r/x18FIH7nWLTyrfeQZJGBy2YqGfNng4EWxpXD/nPmriQ2nxPfoJ5WRi+DTFFtFrkPciOeDtKESICCP4IPVq+7RFnEOg9SE79P3jdd8mw6i4I/Q4+LFk3e8DC02phHYuCjFksw3VsbRKop7VcOxKggMqGdMflipLttX30E7FKaV0D/sy2X7gaf+mn1vJQfZhTO6E5SPq4H6OMg08Eibgn2AMJUB0Wrglsy4YBIgXIdfE3WzyN0MHgPHLh+B2IJgBYseXQ1ifBl6S6XgbHpCGm6KhugUUK3oFuXj3T4Mi4+5/61aUF/FJHHRM8qI0cxB75iwiF/MmvzNq31sY6AKNpiSzC72VnOnGQtp1KQjH5aGnHCbhHS0YvTf+SntTDO8w6ogcqJi1BM4y+qAbEeTSq/PhZzZAIlBSFp1/JOSBpgs1l/4wPqNtXWnop3nxdaIvtosDombCgSn5I=
sudo: false
cache:
  directories:
  - $HOME/.gradle
