language: android
android:
  components:
  - tools
  - tools
  - build-tools-26.0.0
  - android-25
  - extra-android-m2repository
jdk:
- oraclejdk8
after_success:
- build-scripts/deploy_snapshot.sh
env:
  global:
  - secure: Jo55uJMRbyMtio5iJvJGjsj7k82hEz5rnLjDCLjOtfnJWcQD3vni/1v5nZhiXJxxWl3LBXsBvssEUkz/BpT4JNcNPHw25GwsHLdU87/+5j4tQd4ALmKwFh31he9gBbjsuJbdH3+sWnsuY7RBeXmbJRJ2LgkcJ1jiYzjIv8jUDmPkhpQNug9/dO/iWMM42CX5FpeuDIdD0DDv+excUEcIDoooId2BV6dPpHvj7SoGHvQUd4nbkZ4pbCWVi46fIi9fSZiGqPt3lSKxoG2w7SSLETW6s0p6HdhULYNm8LP6zWz3+oeFb03naekh4kOPZIvFt8bB2sf1mzl5mYVN5Sur9iCMyYKks7TFotvMCUDLB8BMo73FGbUF2bzLQiO/OQ43kEeNi5gU/aJAT+V6sIECfKih/Tb2tgQZWjGEidvRx8zOGf71Q/y7njK5NTHWCh5QxaV+HyUxSvjOiU7Fcc/uMlL6dtrB3GbQruY1N9eajpYunl98BWP5JE59I+lQ4dHXrgr3O8Pf4LoAs8X7kEjTYmYcebkRRF3glHfWEUyAchmvFi4Qz/VEGR2OhU6bYcy2g5bUqoHnOox+n+uo/JuRQFcDvztGhdCsHGURuj/CRYhxuk6+6cgzk8gh6XqurWlNDA0/OwBfoLrS73oht2esHjYxN76HnqWdJSn78DkIJEo=
  - secure: L0jNS+kroSBFCLinLzU9ue4e8E0W6veAZiVL6U9DUtidCiVHAqk3fQTq52sB5lnsbJbGuU0w1dPiewym2xe7KhUV2Wze1VzlaOkziugN9Fco6WVd3WRsxlwR6EIt+CqNXUNVKAAyy+o0kVQgUoF9VRp7fdKSxc+EJpKsET52fWQoWb/HVVbfWNS+mmv/GD+Qc2SgwbI39TUPvhrejdbcMZZVusyF2kOJW5g8XhmsBwjeDaYeLaUnPoXsZC2gwkt+QoVa1JMh9IxAFXZVkplF5RdsFjcTrjbkFhXA3/5m25KgwpxBxo4jdrPGBMHFbIz+IfHHmTB9FRjh1PH/omtW0PzZmfAUFsDqaKqXqFqisfatxZf8azzL13CSstH6lf/e/f7w2e2q4VsOoIzoan7EpAf6wHsOGvI61SiDravREHAa4aTAt5uDHi5jK/RDCQEY7/FjP7/4vbxCp+amRzjNn7Hno4JLjnM3CWckvSVX4yYL4+Bm/iEci2q13h1h77b1cyC1ZjOKngZqnC1BDPGzH1x/3Hlv9/mkNHKVlB8M9xN+wiSdVdmf3A7x5msWzJLAwTMZ2I9gSI2BxuC8UlYKtQNidmPO81I6+YoqsfPkBbfznjLb3JhyCahilavfSr/u0zUQTKBigb1FcOBY+tOy0+aRDkohIXdIZCuaYWAOUZ4=
sudo: false
cache:
  directories:
  - $HOME/.gradle
