language: android

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

after_success:
  - build-scripts/deploy_snapshot.sh

env:
  global:
    - secure: "cqfyzS+XFsriwfbeS/O67sHNlpxIdfqYYkkbBOMcUWjxDc/cZ+O31Kw7+G7/GU/ml9fvVqkFk54+4gDeCjZDbcjqCIGsvJt40rDZgiC6mOalgOzAqTbFVcxb6tN/rSQOfQkJiZ7KuMfRSqIzhCMjTcU8MuubD8fxA4LGJKPPMPARdh48ogxtgvQWnRl3wCKqcklZrzerx0QfkKRXPxvdncH7XH/YL27bXEc5fY9UnxcA0h/XAjJV4ftELweYCBFuSq+VDtUE/uRiwJQplEYDUMSi3ylfKLW4JgwHhqFiHsYR6G+KO6G1c5sLg2ZauoTsgwPbPHIGNfCT6BfrasFTJDV9tw26WJe5Jwgow54XJPdY1Ik00v/HyJmECSjHI635qVK3LivjxNPmzIsZVSKtm5YsMlQyS/vNziXRL3eXf47LHBEW0SOVvUs5xOOrwSgCH6xRUEzIMCaGW30OCV0Dh4zC7V0zvzFl1BCaxLxvWxKdfRhOJvrH/y15jYb+SRm1djcJwAzpXK1QY3G+H3JUDyAqqQJ6knhkBZ0wUYOvoXZ+uwmTQIYYukj9ZjBAhhUQtIOhXW+2w946dHbDIFkHmhWIdQz4OyUgHq+ILeHIWoV7naLaUAPj+A/KTmjbIftNbJEYKAMwUN7E6KASHW8vJkBKH283Y/nJQgheXTfZgRE="
    - secure: "baP4UKzreptbUE93aEUfC3HXjUnrjnvLdlbDHnLiGxi4WIiJeCWstqbNgxLCikGTZ66H2VsoR5hRANookgc11G4A702Wxpswla14VIYYVKZ/V+TA4k9hukBTLpZ1zJ0hOPPlVrDjkzzihduIuVJAYBwHjwa2GVzQaqzmmJs63aymIjqdJ5YHoM1CQ6RCqvHnqWLgzvNAZDNIYltAnwdE3R9v1bJKiXmAcPOddiMj+kxcU3HULnnrGFCD0ldfigWk2COcDaCj4Q/hwV3j8sGQGbNQYuJUbpaGotibLqWsRukTEtbwxqVHtXXGSOlkngEW+X6mKE60+O1/lmRKzdY9ARTbmZ3f6Qbp6KCmEh+DXMd9wtjXCtC47A4D2uT+AgVNlZ9z4gg+AdZMxdrya2n9nqRlmLgUx7ZKwqRcqIsLMVh3UohUrfI/UNbe4qnNoOYzLKkuzlOnG3dVc1ptZoLI/PVO9zp54mIus7uldFsAuvTLaCiLD/nJi5Nr437dcg1kR0F0rFwGJJVVwblfQIzNu1Gp9V7VKFeTq+d2W7zHt66lFFtEP6XVDQRTv6e5ALZgN46nh4X+fTE5WPr8B05EFhQfgJnEMjqmNLRr2qiMBSgFCvl1wjXC451oZ0WMhsp6C45c3VrdOAMtjXYqgqMdJv+31pmPu+2KAZeU9266MJo="

sudo: false

cache:
  directories:
    - $HOME/.gradle
